/* OSNova Feature Pack — discovery tools that turn the catalog into a real OS platform. */
(() => {
  const css = `
    .oslab-page{padding-bottom:90px}.oslab-hero{position:relative;overflow:hidden;border:1px solid rgba(115,145,255,.18);border-radius:28px;padding:42px;background:radial-gradient(circle at 85% 20%,rgba(91,92,255,.2),transparent 38%),linear-gradient(135deg,#0d1326,#080d19);box-shadow:0 30px 90px rgba(0,0,0,.28)}
    .oslab-hero h2{font-size:clamp(2.5rem,5vw,5rem);margin:8px 0 14px;letter-spacing:-.05em}.oslab-hero h2 span{background:linear-gradient(90deg,#7c6cff,#19d7ff);-webkit-background-clip:text;background-clip:text;color:transparent}.oslab-hero p{max-width:720px;color:#9ba8c2;font-size:1.05rem}
    .oslab-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px;margin-top:22px}.oslab-card{grid-column:span 4;border:1px solid rgba(120,145,190,.16);background:rgba(13,20,38,.76);border-radius:20px;padding:22px;box-shadow:0 18px 50px rgba(0,0,0,.16)}.oslab-card.wide{grid-column:span 8}.oslab-card.full{grid-column:1/-1}.oslab-card h3{margin:0 0 8px}.oslab-card p{color:#8e9bb4;margin:0 0 16px}.oslab-kpi{font-size:2rem;font-weight:800}.oslab-list{display:grid;gap:9px}.oslab-row{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:10px 12px;border-radius:12px;background:rgba(255,255,255,.035)}.oslab-row button{border:0;background:none;color:inherit;text-align:left;cursor:pointer;font:inherit}.oslab-score{font-weight:800;color:#66ddff}.oslab-meter{height:7px;border-radius:99px;background:#151e32;overflow:hidden;margin-top:7px}.oslab-meter i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#635bff,#22d9ff)}.oslab-tree{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.oslab-tree span{padding:9px 12px;border:1px solid rgba(115,145,255,.22);border-radius:12px;background:rgba(90,100,255,.08)}.oslab-tree b{color:#66728b}.oslab-badges{display:flex;flex-wrap:wrap;gap:9px}.oslab-badge{padding:9px 12px;border-radius:999px;background:linear-gradient(135deg,rgba(98,90,255,.17),rgba(25,215,255,.08));border:1px solid rgba(125,130,255,.2);font-size:.85rem;cursor:pointer}.oslab-check{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.oslab-check label{display:grid;gap:6px;color:#8e9bb4;font-size:.8rem}.oslab-check select{width:100%;padding:11px;border-radius:10px;border:1px solid #25314a;background:#0d1425;color:#e9eefb}.oslab-result{margin-top:14px;padding:14px;border-radius:14px;background:rgba(30,210,150,.06);border:1px solid rgba(30,210,150,.16)}.oslab-health{display:inline-flex;align-items:center;gap:7px;font-size:.78rem}.oslab-dot{width:8px;height:8px;border-radius:50%;background:#42e6a4;box-shadow:0 0 12px #42e6a4}.oslab-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px}@media(max-width:900px){.oslab-card,.oslab-card.wide{grid-column:1/-1}}@media(max-width:600px){.oslab-hero{padding:26px 20px}.oslab-check{grid-template-columns:1fr}.oslab-grid{gap:12px}}
  `;
  const style=document.createElement('style');style.id='osnova-feature-style';style.textContent=css;document.head.appendChild(style);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const avg=s=>Number(s.performance||0);
  function inject(){
    if(document.getElementById('oslab'))return;
    const nav=document.querySelector('.main-nav');
    if(nav){const a=document.createElement('a');a.href='#oslab';a.dataset.page='oslab';a.textContent='OS Lab';nav.insertBefore(a,nav.querySelector('[data-page="compare"]'));a.addEventListener('click',e=>{e.preventDefault();openPage()})}
    const compare=document.getElementById('compare');if(!compare)return;
    const section=document.createElement('section');section.id='oslab';section.className='page oslab-page';section.innerHTML=`
      <div class="oslab-hero"><div class="eyebrow">OSNOVA INTELLIGENCE LAB</div><h2>Go beyond <span>the distro list.</span></h2><p>Explore operating-system families, discover strong matches for your hardware, compare gaming capability, and build your own OS journey.</p><div class="oslab-actions"><button class="btn primary" id="oslabRandom"><i class="fa-solid fa-dice"></i> Random OS</button><button class="btn ghost" id="oslabExplore"><i class="fa-solid fa-compass"></i> Explore catalog</button></div></div>
      <div class="oslab-grid">
        <article class="oslab-card wide"><div class="eyebrow">OS FAMILY MAP</div><h3>See where systems come from</h3><p>A quick visual map of major open operating-system families.</p><div class="oslab-tree"><span>UNIX</span><b>→</b><span>BSD</span><b>→</b><span>FreeBSD</span><span>OpenBSD</span><span>NetBSD</span><b>•</b><span>Linux</span><b>→</b><span>Debian</span><span>Arch</span><span>Fedora</span><span>Alpine</span><span>Independent</span></div></article>
        <article class="oslab-card"><div class="eyebrow">OSNOVA PICKS</div><h3>Top discovery picks</h3><p>Catalog-based highlights, not sponsored rankings.</p><div id="oslabTop" class="oslab-list"></div></article>
        <article class="oslab-card"><div class="eyebrow">HARDWARE LAB</div><h3>Will it fit your PC?</h3><p>Quick compatibility guidance from catalog metadata.</p><div class="oslab-check"><label>GPU<select id="hwGpu"><option value="any">Any</option><option value="amd">AMD</option><option value="nvidia">NVIDIA</option><option value="intel">Intel</option></select></label><label>RAM<select id="hwRam"><option value="4">4 GB</option><option value="8">8 GB</option><option value="16">16 GB</option><option value="32">32 GB+</option></select></label></div><button class="btn primary" id="hwCheck" style="margin-top:12px">Check matches</button><div id="hwResult" class="oslab-result" hidden></div></article>
        <article class="oslab-card wide"><div class="eyebrow">GAMING INTEL</div><h3>Gaming compatibility snapshot</h3><p>See which gaming systems are strongest for Steam, Proton and handheld use.</p><div id="oslabGaming" class="oslab-list"></div></article>
        <article class="oslab-card"><div class="eyebrow">OS JOURNEY</div><h3>Your exploration</h3><p>Build a personal history as you discover new platforms.</p><div class="oslab-kpi" id="oslabHistory">0</div><small>systems explored locally</small><div class="oslab-badges" id="oslabBadges" style="margin-top:15px"></div></article>
        <article class="oslab-card"><div class="eyebrow">DOWNLOAD CENTER</div><h3>Official sources</h3><p>Catalog downloads are intended to point at project sources.</p><div class="oslab-list"><div class="oslab-row"><span>Official links</span><span class="oslab-health"><i class="oslab-dot"></i> Indexed</span></div><div class="oslab-row"><span>No Windows catalog</span><span class="oslab-health"><i class="oslab-dot"></i> Open alternatives</span></div><div class="oslab-row"><span>Architecture metadata</span><span class="oslab-health"><i class="oslab-dot"></i> Indexed</span></div></div></article>
        <article class="oslab-card full"><div class="eyebrow">FAST DISCOVERY</div><h3>Jump into a category</h3><div class="oslab-badges"><button class="oslab-badge" data-oslab-type="Linux">Linux</button><button class="oslab-badge" data-oslab-type="Gaming">Gaming</button><button class="oslab-badge" data-oslab-type="BSD">BSD</button><button class="oslab-badge" data-oslab-type="Mobile">Mobile</button><button class="oslab-badge" data-oslab-type="Alternative">Alternative</button><button class="oslab-badge" data-oslab-type="Media">Media / HTPC</button></div></article>
      </div>`;
    compare.parentNode.insertBefore(section,compare);
    section.querySelector('#oslabExplore').onclick=()=>{location.hash='explore';window.app?.showPage('explore')};
    section.querySelector('#oslabRandom').onclick=()=>window.app?.surpriseMe?.();
    section.querySelector('#hwCheck').onclick=hardwareCheck;
    section.querySelectorAll('[data-oslab-type]').forEach(b=>b.onclick=()=>{location.hash='explore?type='+encodeURIComponent(b.dataset.oslabType);window.app?.showPage('explore')});
    renderInsights();
  }
  function renderInsights(){const app=window.app;if(!app)return;const top=[...app.systems].sort((a,b)=>avg(b)-avg(a)).slice(0,5);const el=document.getElementById('oslabTop');if(el)el.innerHTML=top.map(s=>`<div class="oslab-row"><button onclick="app.openById('${esc(s.id)}')">${esc(s.name)}</button><span class="oslab-score">${avg(s)?avg(s)+'/10':'OPEN'}</span></div>`).join('');const games=[...app.gaming].sort((a,b)=>Number(b.performance||0)-Number(a.performance||0)).slice(0,5);const ge=document.getElementById('oslabGaming');if(ge)ge.innerHTML=games.map(s=>`<div><div class="oslab-row"><button onclick="app.openGaming('${esc(s.id)}')">${esc(s.name)}</button><span>${esc(s.steam||'—')}</span></div><div class="oslab-meter"><i style="width:${Math.min(100,Number(s.performance||0)*10)}%"></i></div></div>`).join('');const hist=app.history||[];const he=document.getElementById('oslabHistory');if(he)he.textContent=hist.length;const badges=document.getElementById('oslabBadges');if(badges){const out=[];if(hist.length>=1)out.push('First Explorer');if(hist.length>=10)out.push('OS Explorer');if(hist.length>=25)out.push('Platform Scout');if((app.favorites||new Set()).size>=5)out.push('Collector');badges.innerHTML=out.map(x=>`<span class="oslab-badge">${x}</span>`).join('')||'<span class="oslab-badge">Start exploring to unlock badges</span>'}}
  function hardwareCheck(){const app=window.app;if(!app)return;const ram=Number(document.getElementById('hwRam')?.value||8);const el=document.getElementById('hwResult');const candidates=app.systems.filter(s=>{const cats=(s.category||[]).join(' ').toLowerCase();const text=[s.description,s.useCases,...(s.architecture||[])].join(' ').toLowerCase();return ram>4||cats.includes('lightweight')||cats.includes('old hardware')||text.includes('lightweight')}).slice(0,6);el.hidden=false;el.innerHTML=candidates.length?`<b>Good starting points:</b><br>${candidates.map(s=>`<button class="text-btn" onclick="app.openById('${esc(s.id)}')">${esc(s.name)}</button>`).join(' • ')}`:'No strong catalog match found.'}
  function openPage(){if(!window.app)return;window.app.showPage('oslab');location.hash='oslab';renderInsights()}
  function patchRouting(){const app=window.app;if(!app||app.__osnovaPatched)return;app.__osnovaPatched=true;const original=app.showPage.bind(app);app.showPage=(p,scroll=true)=>{if(p==='oslab'){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='oslab'));document.querySelectorAll('.main-nav a').forEach(x=>x.classList.toggle('active',x.dataset.page==='oslab'));if(scroll)window.scrollTo({top:0,behavior:'smooth'});renderInsights();return}original(p,scroll)};window.addEventListener('hashchange',()=>{if(location.hash.replace('#','').split('?')[0]==='oslab')app.showPage('oslab',false)})}
  function boot(){inject();patchRouting();renderInsights()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,50),{once:true});else setTimeout(boot,50);
})();
