/* OSPulse profile settings. Uses only Supabase Auth + the user's own profiles row. */
(() => {
  const sbApi = () => window.DistroHubSupabase;
  let modal, oldAccount;

  function esc(v){return String(v ?? '').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
  function show(msg='', type=''){const el=document.getElementById('profileMessage');if(el){el.textContent=msg;el.className='profile-message '+type;}}
  function initials(name,email){const s=(name||email||'U').trim();return s.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}

  function build(){
    if(document.getElementById('profileModal')) return;
    document.body.insertAdjacentHTML('beforeend',`<div class="profile-modal" id="profileModal" aria-hidden="true"><div class="profile-backdrop"></div><section class="profile-card" role="dialog" aria-modal="true" aria-labelledby="profileTitle"><button class="profile-close" id="profileClose" aria-label="Close"><i class="fa-solid fa-xmark"></i></button><div class="profile-head"><div class="profile-avatar" id="profileAvatar">U</div><div><h2 id="profileTitle">Your account</h2><p id="profileSubtitle">Manage your OSPulse profile</p></div></div><div class="profile-tabs"><button class="profile-tab active" data-profile-tab="account">Account</button><button class="profile-tab" data-profile-tab="security">Security</button><button class="profile-tab" data-profile-tab="activity">Activity</button></div><div class="profile-panel active" data-profile-panel="account"><form class="profile-form" id="profileForm"><label>Username<input id="profileUsername" type="text" maxlength="40" minlength="2" autocomplete="username" placeholder="Your username"></label><label>Email<input id="profileEmail" type="email" autocomplete="email" placeholder="you@example.com"></label><div class="profile-email-note">Changing your email may require confirmation from the new address.</div><div class="profile-actions"><button class="btn primary" type="submit"><i class="fa-solid fa-check"></i> Save changes</button></div><div class="profile-message" id="profileMessage" aria-live="polite"></div></form></div><div class="profile-panel" data-profile-panel="security"><form class="profile-form" id="passwordForm"><label>New password<input id="profilePassword" type="password" minlength="8" autocomplete="new-password" placeholder="At least 8 characters"></label><label>Confirm new password<input id="profilePassword2" type="password" minlength="8" autocomplete="new-password" placeholder="Repeat your password"></label><div class="profile-actions"><button class="btn primary" type="submit"><i class="fa-solid fa-key"></i> Change password</button></div><div class="profile-message" id="securityMessage" aria-live="polite"></div></form></div><div class="profile-panel" data-profile-panel="activity"><div class="profile-stats"><div class="profile-stat"><strong id="profileFavs">0</strong><span>Favorites</span></div><div class="profile-stat"><strong id="profileHistory">0</strong><span>Recently viewed</span></div><div class="profile-stat"><strong id="profileComparisons">0</strong><span>Comparisons</span></div></div><div class="profile-info"><div><span>Member since</span><strong id="profileCreated">—</strong></div><div><span>Account email</span><strong id="profileEmailInfo">—</strong></div></div></div><div class="profile-actions" style="margin-top:24px"><button class="profile-danger" id="profileSignOut"><i class="fa-solid fa-right-from-bracket"></i> Sign out</button></div></section></div>`);
    modal=document.getElementById('profileModal');
    document.getElementById('profileClose').onclick=close;
    modal.querySelector('.profile-backdrop').onclick=close;
    modal.querySelectorAll('[data-profile-tab]').forEach(btn=>btn.onclick=()=>switchTab(btn.dataset.profileTab));
    document.getElementById('profileForm').onsubmit=saveProfile;
    document.getElementById('passwordForm').onsubmit=changePassword;
    document.getElementById('profileSignOut').onclick=signOut;
  }
  function switchTab(tab){modal.querySelectorAll('[data-profile-tab]').forEach(x=>x.classList.toggle('active',x.dataset.profileTab===tab));modal.querySelectorAll('[data-profile-panel]').forEach(x=>x.classList.toggle('active',x.dataset.profilePanel===tab));}
  async function open(){build();const api=sbApi();const user=await api?.currentUser();if(!user){window.app?.openAuth();return;}const client=await api.loadClient();if(!client)return;let profile=null;try{const r=await client.from('profiles').select('username,created_at').eq('id',user.id).maybeSingle();profile=r.data||null;}catch(e){}document.getElementById('profileUsername').value=profile?.username||user.user_metadata?.username||'';document.getElementById('profileEmail').value=user.email||'';document.getElementById('profileEmailInfo').textContent=user.email||'—';document.getElementById('profileCreated').textContent=user.created_at?new Date(user.created_at).toLocaleDateString(): '—';document.getElementById('profileAvatar').textContent=initials(profile?.username,user.email);document.getElementById('profileTitle').textContent=profile?.username||'Your account';document.getElementById('profileSubtitle').textContent=user.email||'Manage your OSPulse profile';document.getElementById('profileFavs').textContent=window.app?.favorites?.size??0;document.getElementById('profileHistory').textContent=window.app?.history?.length??0;document.getElementById('profileComparisons').textContent=window.app?.comparisons?.length??0;show('');switchTab('account');modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
  function close(){if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true');}
  async function saveProfile(e){e.preventDefault();show('');const api=sbApi(), client=await api?.loadClient(), user=await api?.currentUser();if(!client||!user)return show('Please sign in again.','error');const username=document.getElementById('profileUsername').value.trim();const email=document.getElementById('profileEmail').value.trim();if(username.length<2)return show('Username must be at least 2 characters.','error');try{const p=await client.from('profiles').update({username}).eq('id',user.id);if(p.error)throw p.error;if(email!==user.email){const r=await client.auth.updateUser({email});if(r.error)throw r.error;show('Profile saved. Check your new email to confirm the address.','success');}else show('Profile saved successfully.','success');document.getElementById('profileTitle').textContent=username;document.getElementById('profileAvatar').textContent=initials(username,email);document.getElementById('profileEmailInfo').textContent=email;refreshAccountButton(username);}catch(err){console.error(err);show(err.message||'Could not save profile.','error');}}
  async function changePassword(e){e.preventDefault();const msg=document.getElementById('securityMessage');msg.textContent='';msg.className='profile-message';const a=document.getElementById('profilePassword').value,b=document.getElementById('profilePassword2').value;if(a.length<8)return Object.assign(msg,{textContent:'Password must be at least 8 characters.',className:'profile-message error'});if(a!==b)return Object.assign(msg,{textContent:'Passwords do not match.',className:'profile-message error'});const client=await sbApi()?.loadClient();if(!client)return;const r=await client.auth.updateUser({password:a});if(r.error){msg.textContent=r.error.message;msg.className='profile-message error';}else{msg.textContent='Password changed successfully.';msg.className='profile-message success';e.target.reset();}}
  async function signOut(){const client=await sbApi()?.loadClient();if(client)await client.auth.signOut();close();window.app?.handleSignedOut?.();refreshAccountButton('');window.app?.toast?.('Signed out successfully.');}
  function refreshAccountButton(username){const btn=document.getElementById('accountBtn');if(!btn)return;btn.classList.toggle('logged-in',!!username);const label=document.getElementById('accountLabel');if(label)label.textContent=username||'Sign in';}

  function install(){build();oldAccount=document.getElementById('accountBtn');if(!oldAccount)return;const replacement=oldAccount.cloneNode(true);oldAccount.replaceWith(replacement);replacement.addEventListener('click',open);window.addEventListener('osPulseAuthChanged',e=>{const u=e.detail?.user;if(u){refreshAccountButton(e.detail.username||u.user_metadata?.username||u.email?.split('@')[0]||'Account');}else refreshAccountButton('');});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
